name: 'Run Deploy Action'
on:
  workflow_dispatch:
    inputs:
      who-to-call:
        required: true



jobs:
  deploy_through_action_job:
    runs-on: ubuntu-latest
    name: Deploying through action
    steps:
      - id: deployAction
        uses: JavierIbanezSoloaga/cross-platform-actions@bug/do_not_end_if_run_never_complete
        with:
          who-to-call: ${{ inputs.who-to-call }}
          token: ${{ secrets.TOKEN }}
      # - name: Get the output
      #   run: |
      #     curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" ${{ steps.deployAction.outputs.deploy-artifact }} > artifact.zip
      - name: Print artifact
        run: cat ${{ steps.deployAction.outputs.deploy-artifact }}
