name: 'Run Deploy Action'
on:
  workflow_dispatch:
    inputs:
      who-to-call:
        required: true



jobs:
  deploy_throught_action_job:
    runs-on: ubuntu-latest
    name: Deploying throught action
    steps:
      - id: deployAction
        uses: JavierIbanezSoloaga/cross-platform-actions@main
        with:
          who-to-call: ${{ inputs.who-to-call }}
          token: ${{ secrets.TOKEN }}
      - name: Get the output
        run:  |
          artifact=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" ${{ steps.deployAction.outputs.deploy-artifact }})
      - name: Unzip the artifact
        run: cat $artifact
