name: 'Run composite Action'
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: JavierIbanezSoloaga/hello-world-composite-action@v1
        with:
          who-to-greet: 'Javier'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
        
  hello_world_javascript:
    runs-on: ubuntu-latest
    name: Say hello but from javascript action
    steps:
      - id: jsGreet
        uses: JavierIbanezSoloaga/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Javier'
      - run: |
          echo time ${{ steps.jsGreet.outputs.time }}
        shell: bash
