name: ID Example

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.id1 }}
    steps:
      - id: step1
        name: ${{ github.event.inputs.id }}
        run: |
          echo "id1={{inputs.id}}" >> $GITHUB_OUTPUT
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Create an artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-artifact
          path: testFolder/hello.txt
  
  printId:
    name: Print ID
    runs-on: ubuntu-latest
    needs: id
    steps:
      - id: test
        run: echo ${{needs.id.outputs.output1}}
