name: ID Example

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    outputs:
      outpt: ${{ steps.step1.outputs.id }}
    steps:
      - id: step1
        name: ${{ github.event.inputs.id }}
        # run: echo id = asf${{ inputs.id }} >> "$GITHUB_OUTPUT"
        run: echo ::set-output name=id::${{inputs.id}}
  
  printId:
    name: Print ID
    runs-on: ubuntu-latest
    needs: id
    steps:
      - id: test
        run: echo ${{needs.id.outputs.outpt}}
